### ISSUE TITLE
[JUV-103] 네이버 클로바 연동 객체 생성하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#11]
# 🍀  네이버 클로바 연동 객체 생성하기 <br/><br/>

## 📓  Todo

- [ ] 클로바 연동 객체 구상하기
- [ ] 적당한 추상화를 고민해보기
- [ ] 클로바를 거치는 테스트 코드 작성하기
- [ ] 클로바를 거치지 않는 테스트 코드 작성하기
- [ ] 구현된 코드 릴리즈 브렌치에 머지하고 더블체크하기
