### ISSUE TITLE
[JUV-103] 네이버 클로바 연동 객체 생성하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#12]
# 🍀  네이버 클로바 연동 객체 생성하기 <br/><br/>

## 📓  Todo

- [x] 클로바 연동 객체 구상하기
- [x] 적당한 추상화를 고민해보기
- [x] 클로바가 아닌 다른 AI API로 변경될 가능성도 고려해보기
- [x] 클로바를 거치는 테스트 코드 작성하기
- [x] 클로바를 거치지 않는 테스트 코드 작성하기

**Comment by PunRabbit** [comment]
**🧪 Python 테스트 코드 도구는 Unittest 를 사용!**

Pytest 보다 덜 깔끔하다고 보여질 수 있지만, 이쪽이 더 클래식하고 보편적인 스타일이라고 생각 합니다 :>

**Comment by PunRabbit** [comment]
**🤔  Clova를 하나의 로직이라 생각하고 In/Out을 명확히 한다면...?**

일단 대강의 클래스는 만들어보았음!
다른 AI로 교체되더라도 안에서 요구하는 계약사항을 동일하게 이행하고 Out이 동일한 DTO를 반환하도록 추상화한다면..?
괜찮지 않을까..?

**Comment by PunRabbit** [comment]
**🍡  Clova로 직접 요청하는 테스트 코드 작성 완료!**

좀 더 세부적이고 명확한 테스트 코드가 필요할 듯 하지만...
일단은 간단하게라도 추가!
너무 세세하고 많은 고민은 개발을 너무 늦추니까...!!

**Comment by PunRabbit** [comment]
**😶‍🌫️  Mocking을 통한 가짜 RequestsModule 테스트 코드 작성 완료!**

근데 제대로 쓴 것 같지는 않다.
특정 객체를 patch하는 과정이 더 세련될 수 있을 것 같은데...
추후에 필히 수정이 필요할 듯 함!
