### ISSUE TITLE
[JUV-006] 테스트용 데이터베이스 구축하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#13]
# 🗡️    원격 서버에 테스트용 데이터베이스 구축합니다. <br/><br/>

## 📓  Todo

- [x] Mysql Docker 버전으로 설치하기
- [x] 원격 접속을 위한 포트 설정과 데이터베이스 설정 반영하기
- [x] 원격 접속 테스트하기

**Comment by PunRabbit** [comment]
**🔚  원격 서버에 docker-compose를 통해 mysql을 구축하였으며, 테스트를 위한 포트를 별도로 열어서 원격 접속 테스트를 완료했습니다.**

일단 테스트를 위한 임시 데이터베이스지만,

운영 중 컨테이너 증발로 인한 데이터 유실을 막기 위해 원격 서버에 데이터 폴더를 마운트해뒀습니다. 😄
