### ISSUE TITLE
[JUV-104] Slack Message 전송 객체 생성하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#14]
# 🍨   Slack Message 전송 객체 생성하기 <br/><br/>

## 📓  Todo

- [x] Slack 채널 생성하기
- [x] Slack Token 발급 및 Bot 생성하기
- [x] 연동 테스트하기
- [x] 서버에 붙여서 테스트하기
- [x] 커스텀 메세지 작성하기

**Comment by PunRabbit** [comment]
**🌵 Slack 채널 오픈하고 Token 발급해서 Bot 추가 완료!**

Python 코드로 채널에 간단한 메세지도 발신 완료!

<img width="205" alt="스크린샷 2022-09-06 오후 7 29 33" src="https://user-images.githubusercontent.com/70463212/188613105-c3eedbd7-c13a-4662-b4c7-bd7c28f7974c.png">

**Comment by PunRabbit** [comment]
**🧪  서버에 붙여서 실행 테스트 완료!**

딱히 별 문제 없이 돌아가는 것을 확인!
사실 알림이 필요한 부분에 편하게 붙여서 사용할 수 있도록 더 컴팩트하게 구성해보는게 필요하다고 생각됨!

**Comment by PunRabbit** [comment]
**🏄 Slack Block Kit Builder를 이용해서 간단한 샘플 완성!**

아래 링크로 들어가서 입맛대로 커스텀!
https://app.slack.com/block-kit-builder/T03T9USEA76#%7B%22blocks%22:%5B%5D%7D

알림 템플릿과 관련하여 좀 더 세련된 코드 구현 방법이 있을 것 같은데...
이건 좀 더 고민해보고 차후 리팩토링 때 신경써야 할 듯!
