### ISSUE TITLE
[JUV-105] 이미지 전송 객체 생성하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#19]
# 🎨 이미지 전송 객체 생성하기 <br/><br/>

## 📓  Todo

- [ ] 이미지 전송 방식 결정하기
- [ ] 이미지 저장 엔드포인트 결정하기 (구글드라이브, 오라클 서버 etc...)
- [ ] 이미지 지정 포맷 및 해상도 재구성 여부 결정하기
- [ ] 이미지 최대 전송 크기 및 개수 산정하기
- [ ] 이미지 전송 객체 생성하기
