### ISSUE TITLE
[JUV-001] 레포지토리 젠킨스 연동

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#2]
# ⛏️  레포지토리와 젠킨스를 연동하여 CI/CD 환경을 구축합니다. <br/><br/>

## 📓  Todo

- [x] 배포 서버에 젠킨스 구축하기
- [x] 젠킨스에 깃허브 토큰 등록하고 테스트하기
- [ ] Master 브렌치와 젠킨스 연동하기
- [x] Release 브렌치와 젠킨스 연동하기
- [ ] Master 브렌치에 적합한 Stage 구성하기
- [ ] Release 브렌치에 적합한 Stage 구성하기
- [ ] 실제 배포에 문제가 없는지 테스트하기
- [ ] 배포 서버와 젠킨스 분리하기

**Comment by PunRabbit** [comment]
**🎶  오라클에 Docker로 구축 완료!**

**Comment by PunRabbit** [comment]
**🪙  깃허브 토큰 등록 후 테스트 완료!**
