### ISSUE TITLE
[JUV-106] 데이터베이스 추상화/구현체 객체 생성하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#20]
# ☁️ 데이터베이스 추상화/구현체 객체 생성하기 <br/><br/>

## 📓  Todo

- [x] 연동 데이터베이스 종류 파악하기
- [x] 사용 라이브러리 종류 파악하기
- [x] 데이터베이스 공통점 산출하기
- [x] 추상화 객체 생성하기
- [x] 구현체 생성하기

**Comment by PunRabbit** [comment]
**🏃 일단 pymysql, sqlalchemy 기준 query 직접 입력 방식으로 진행!!**

각 라이브러리에 맞는 테스트코드도 간단하게 작성해뒀습니다.
차후에 좀 더 손봐야 할 것 같아요.
