### ISSUE TITLE
[JUV-109] Coverage 적용하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#25]
# 🏁  Coverage 적용하기 <br/><br/>

## 📓  Todo

- [x] Coverage 라이브러리 찾아보기
- [x] 현재 서버에 적용된 TestCode 방식과 접목해보기
- [x] Coverage 기준점 정하기
- [x] 해당 기준점 기준으로 Server 실행 여부 결정하기

**Comment by PunRabbit** [comment]
**👟  python coverage 라이브러리로 결정!**

현재 커버리지 기준을 80 정도로 잡았는데 테스트코드들을 미포함하면 아무래도 어려운 수치이지 않을까...
그래도 일단 80으로 잡고 진행해보자!
