### ISSUE TITLE
[JUV-002] 배포 서버 환경설정하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#3]
# ⛏️  배포 서버 사양을 확인하고 적합한 환경을 구축합니다. <br/><br/>

## 📓  Todo

- [x] Oracle Free Tier 최대 사양 확인하기
- [x] 서버 제약사항 확인하기
- [x] Port 개방, ssh 접속 허용 등 기본적인 설정 진행하기
- [x] 기본 Storage, Memory 확인하기
- [x] 실운용으로 자원이 적합한지 예측하기

**Comment by PunRabbit** [comment]
**💻  Oracle Free Tier 무료 계정 기본 사양**

VM.Standard.E2.1Micro 구성
1/8 OCPU 프로세서
1GB 메모리 
100GB 저장공간 (50GB 기본 인스턴스 올린 후 추가적으로 50GB 할당하여 마운트 진행함)

**Comment by PunRabbit** [comment]
**🔗  서버 제약사항 확인 결과 실운영에 문제될만한 사항은 없어보임!**

단, 네트워크 속도가 조금 튀는 경향이 있는 듯 함

**Comment by PunRabbit** [comment]
**⚡  필요 포트 개방 완료**

**Comment by PunRabbit** [comment]
**💭  기본 메모리가 1GB...??**

실험삼아 Docker로 ELK Stack을 띄워보았는데, 아니나 다를까 메모리 부족으로 다운.
추가적인 비용을 지불하면서 운영하기에는 조금 부담스러운 측면이 있기에...
일단은 Swap Memory로 4GB를 추가 할당 해둠!

**Comment by PunRabbit** [comment]
**🐕  Docker로 작업한 Nginx를 잘못 건드렸다가 고장나서 생고생했다.**

설정을 뭘 잘못 건드렸는지 80, 443 포트에 대한 방화벽이 갑자기 닫힌 듯 하다.
아래 블로그를 참고하여 겨우 해결!
https://pythonblog.co.kr/blog/30/

**Comment by PunRabbit** [comment]
**🧪  실 자원 소비량에 대한 세세한 측정량을 테스트 한 것은 아니지만 간단한 테스트 진행 완료!**

CPU 사용량이 매우매우 모자라나... (뚝뚝 떨어지다 못해 죽으려 한다.)
일단 억지로 어찌어찌 굴러가는 상태.
나중에 유료 정책을 결제해서 서버를 이전하는게 좋을 듯 하다.
