### ISSUE TITLE
[JUV-003] 네이버 클로바 OCR API 설정하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#4]
# 🍀   서버에 필요한 네이버 클로바 OCR API를 설정합니다. <br/><br/>

## 📓  Todo

- [x] 네이버 클로바 OCR 무료 계정 생성하기
- [x] 네이버 클로바 API GateWay 설정하기
- [x] 네이버 클로바 자체제공 API테스트 실행하기

**Comment by PunRabbit** [comment]
**💳  계정 생성 완료!**

무료버전이라 한계치에 도달 시 자동 Lock이 걸리지만, 결제수단이 등록되어 있으므로 조심 또 조심...

**Comment by PunRabbit** [comment]
**🚪  API GateWay 설정 완료!**

게이트웨이 무료 제공 호출수는 1,000,000개!
Text OCR만 사용하기에는 문제없을듯함!

**Comment by PunRabbit** [comment]
**❗  웹툰 효과 표현 텍스트 인식률 이슈**

![나이트런 OCR](https://user-images.githubusercontent.com/70463212/180600290-54c6fc4b-bdeb-4f62-803f-0e0734155a92.png)

네이버 나이트런의 장면 일부를 Demo OCR로 돌린 결과
효과를 표현하는 텍스트에 대해서는 인식률이 매우 낮음

단순 OCR에만 의존하여 오타/비속어를 필터링하기에는 무리가 있을 듯 함

**Comment by PunRabbit** [comment]
**🧳 Clove 연동 테스트 완료**

Python requests 모듈을 통해서도 연동이 되는걸 확인!
사소한 문제라면, 구글 드라이브와의 연동이 안되는 듯 함.
다른 이미지 호스팅 서버를 찾아야 할 것 같음...
