### ISSUE TITLE
[JUV-004] Notion API 연동하여 방문 기록 시각화하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#5]
# 📔  Notion API 연동하여 방문기록 남기기 <br/><br/>

## 📓  Todo

- [x] Notion 아이디 생성하기
- [x] Notion API 생성하기
- [x] Notion API 연동 테스트해보기
- [ ] 적합한 시각화 검토, 적용하기

**Comment by PunRabbit** [comment]
**🆔  아이디 생성 완료!**

**Comment by PunRabbit** [comment]
**😮  API 생성, Curl을 통한 테스트 완료!**
