### ISSUE TITLE
[JUV-101] 프로젝트 기본 폴더구조 생성하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#8]
# ✍️   프로젝트의 기본 폴더구조를 생성합니다. <br/><br/>

## 📓  Todo

- [ ] MVC Pattern 반영해보기
- [ ] Domain Driven Design (DDD) 반영해보기
- [ ] Hexagonal Architecture 반영해보기
- [ ] 추가적인 개인 아이디어 반영해보기
- [x] 폴더구조 생성하여 브렌치에 반영하기

**Comment by PunRabbit** [comment]
**📝  Architecture 구조에 대한 좋은 글 메모!**

https://engineering.linecorp.com/ko/blog/port-and-adapter-architecture/

https://velog.io/@roo333/지속-가능한-소프트웨어-설계-패턴-Hexagonal-Architecture

**Comment by PunRabbit** [comment]
**😢  Architecture 구조를 제대로 이해했다고 할 수 없기에 체크박스를 체크할 수 없어요**

하지만 여기서 병목이 생길 수 없기 때문에, 일단 스스로 이해한 것들만 빠르게 브렌치에 반영해봅니다...!

**Comment by PunRabbit** [comment]
#9 [JUV-102] 이슈로 남은 이슈들 이관합니다.
