### ISSUE TITLE
[JUV-102] 프로젝트 구조 개선하기

### ISSUE THREAD

**Issue by PunRabbit** [PunRabbit/Juniverse#9]
> #8 [JUV-101] 에서 해결하지 못한 부분들을 이관해서 작성합니다.

<br/>

# ✍️   현재의 프로젝트 구조를 개선합니다. <br/><br/>

## 📓  Todo

- [ ] MVC Pattern 반영해보기
- [ ] Domain Driven Design (DDD) 반영해보기
- [ ] Hexagonal Architecture 반영해보기
- [ ] 추가적인 개인 아이디어 반영해보기

**Comment by PunRabbit** [comment]
**🚦  Semi 프로젝트 개선을 거쳤습니다!**

어렵게 생각하지 않고, 느끼는 대로 한번 가볍게 개선해봤습니다.

관련 태그! (#21) / (#22)
